// This Source Code Form is subject to the terms of the Mozilla Public
// License, v. 2.0. If a copy of the MPL was not distributed with this
// file, You can obtain one at https://mozilla.org/MPL/2.0/.

//go:build ignore

// gen writes extpict.go from the Unicode file emoji-data.txt:
//
//	go run gen.go -in emoji-data.txt -version 15.0.0
package main

import (
	"bufio"
	"flag"
	"fmt"
	"go/format"
	"log"
	"os"
	"slices"
	"strconv"
	"strings"
)

func main() {
	in := flag.String("in", "emoji-data.txt", "path to emoji-data.txt")
	version := flag.String("version", "", "Unicode version of the input")
	flag.Parse()
	f, err := os.Open(*in)
	if err != nil {
		log.Fatal(err)
	}
	defer f.Close()
	var ranges [][2]rune
	sc := bufio.NewScanner(f)
	for sc.Scan() {
		line, _, _ := strings.Cut(sc.Text(), "#")
		cps, prop, ok := strings.Cut(line, ";")
		if !ok || strings.TrimSpace(prop) != "Extended_Pictographic" {
			continue
		}
		lo, hi, isRange := strings.Cut(strings.TrimSpace(cps), "..")
		if !isRange {
			hi = lo
		}
		a, err1 := strconv.ParseUint(lo, 16, 32)
		b, err2 := strconv.ParseUint(hi, 16, 32)
		if err1 != nil || err2 != nil {
			log.Fatalf("bad line %q", sc.Text())
		}
		ranges = append(ranges, [2]rune{rune(a), rune(b)})
	}
	if err := sc.Err(); err != nil {
		log.Fatal(err)
	}
	slices.SortFunc(ranges, func(x, y [2]rune) int { return int(x[0] - y[0]) })
	var merged [][2]rune
	for _, r := range ranges {
		if n := len(merged); n > 0 && r[0] <= merged[n-1][1]+1 {
			merged[n-1][1] = max(merged[n-1][1], r[1])
			continue
		}
		merged = append(merged, r)
	}
	var b strings.Builder
	b.WriteString("// This Source Code Form is subject to the terms of the Mozilla Public\n// License, v. 2.0. If a copy of the MPL was not distributed with this\n// file, You can obtain one at https://mozilla.org/MPL/2.0/.\n\n")
	fmt.Fprintf(&b, "// Code generated by gen.go from emoji-data.txt of Unicode %s. DO NOT EDIT.\n\npackage textcheck\n\n", *version)
	b.WriteString("// extPict lists the code points with the Unicode property\n// Extended_Pictographic as sorted, merged ranges.\nvar extPict = [][2]rune{\n")
	for _, r := range merged {
		fmt.Fprintf(&b, "\t{0x%04X, 0x%04X},\n", r[0], r[1])
	}
	b.WriteString("}\n")
	src, err := format.Source([]byte(b.String()))
	if err != nil {
		log.Fatal(err)
	}
	if err := os.WriteFile("extpict.go", src, 0o644); err != nil {
		log.Fatal(err)
	}
}
